### ISSUE TITLE
Large AppMaps are handled the same way as VS Code handles them

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#244]
This work was recently done in VS Code:
https://appmap.io/docs/reference/handling-large-appmaps.html

Some of the issues related included these:
https://github.com/getappmap/vscode-appland/issues/651
https://github.com/getappmap/appmap-js/issues/1114

**Comment by jansorg** [comment]
@brikelly @ahtrotta  Could you add a high-level overview of the needed steps?
I looked into the VSCode commits, but I'm not sure if we're on the same page.

- Should the plugin detect a large AppMap and execute the CLI to prune such a map?
- Should this happen in-memory or is the pruned AppMap persisted on disk? Is the original file overwritten?
- Is the CLI prune command adding the new properties to the AppMap.json?

**Comment by ahtrotta** [comment]
Sure! A lot of the logic for the VS Code extension is [here](https://github.com/getappmap/vscode-appland/blob/master/src/editor/appmapEditorProvider.ts#L108). Also, a precursor to this work is to [execute the stats CLI command](https://github.com/getappmap/vscode-appland/blob/master/src/editor/appmapEditorProvider.ts#L171) and send that information to the webview (relevant commit [here](https://github.com/getappmap/vscode-appland/commit/18c8d288ac40077865af5b790da1eaab0ed67e80)). To answer your questions:

- Yes, the plugin should detect a large appmap ( > 10 MB) and [execute the prune CLI command](https://github.com/getappmap/vscode-appland/blob/master/src/editor/appmapEditorProvider.ts#L149) on the map. The plugin should also detect a giant appmap ( > 200 MB) and then **not** read the file contents. Instead, the extension should send an empty object as appmap data, and run the stats CLI command and attach the results to the data that gets sent to the webview (the `stats` property is at the same level as `events`, `classMap`, and `metadata`).
- This happens in memory, so the original file remains unchanged.
- When a map gets pruned by the extension, the data that is produced has a `pruneFilter` property (at the same level as the `events`, `classMap`, etc). This needs to be sent to the webview to have it render correctly. This property is not persisted to disk since the prune command does not alter the appmap file when the `--output-data` option is used.

So the argument that gets sent to the `loadData` command for the webview should have all of these properties for a pruned appmap:
```
{
  events: [<DATA>],
  classMap: [<DATA>],
  findings: [<DATA_IF_APPLICABLE>],
  metadata: [<DATA>],
  stats: {<DATA>},
  pruneFilter: {<DATA>}
}
```

Please let me know if something is not clear!

**Comment by jansorg** [comment]
@ahtrotta The JS implementation of the stats command is using `Number.MAX_SAFE_INTEGER`. How is this value used and must I pass the same value or may I rely on Java's `Long.MAX_VALUE` or similar?

**Comment by jansorg** [comment]
@ahtrotta Do I have to attach the stats to all AppMap files, i.e. also to files smaller than 10mb?

**Comment by ahtrotta** [comment]
> @ahtrotta The JS implementation of the stats command is using `Number.MAX_SAFE_INTEGER`. How is this value used and must I pass the same value or may I rely on Java's `Long.MAX_VALUE` or similar?

You can use Java's `Long.MAX_VALUE`. I was just making sure that the output was limited to the default of `10`, so I used a very large number.


> @ahtrotta Do I have to attach the stats to all AppMap files, i.e. also to files smaller than 10mb?

Yes, that would be good. It's not a strict requirement, but if the `stats` field is missing then the user won't see the `stats` button in the top right corner. The map should still load just fine otherwise.

**Comment by ahtrotta** [comment]
I think the problem is that the `stats` property needs to be an object with a `functions` property that has the value of the JSON array returned by the CLI stats command. I'm sorry I didn't make this clear above. So it should look like this:
```
{
  stats: {
    functions: [<STATS_DATA>],
  },
}
```
You can see an example [here](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/stories/data/scenario.json#L9068).
