### ISSUE TITLE
Python app installation failed in PyCharm

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#346]
The console output looks messed up and garbled somewhat. PyCharm CE 2023.2, latest AppMap plugin (0.44).
See https://www.loom.com/share/bd20cf55d4c243db934ffd0ee031200a?sid=e0630fa6-30fa-42f3-b630-81e41c58af5e

**Comment by jansorg** [comment]
@brikelly If this is only about the JSON parsing error, then I'm unsure what do about it. The parsing error originates in the AppMap installer code, see `agentInstallerProcedure.js` in the stacktrace. The installer seems to run a pip/python command and is then unable to parse the JSON. IMO this has to be fixed in the AppMap installer code.
