### ISSUE TITLE
Refactor telemetry to match VSCode

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-intellij-plugin#398]
https://github.com/getappmap/vscode-appland/pull/790 refactored VSCode telemetry to remove unreliable events and focus on error reporting. We should roll these changes over to JetBrains as well.

**Comment by jansorg** [comment]
Based on https://github.com/getappmap/appmap-intellij-plugin/issues/424, the following events would be removed:
- view:open
- click_docs_link_in_tree
- clicked_sign_in_link
- click_tab
- select_object_in_sidebar
- analysis:view_finding
- analysis:view_overview
- analysis:cta_interaction
- authentication:success
- authentication:sign_out
- plugin:install
- appmap:create
- appmap:open
- sidebar_search_focused
- click_filter_button
- reset_diagram

The following would remain:
- run_config:incompatible_jdk (only sent by the JetBrains plugin, I suppose)
- run_config:execute (only sent by the JetBrains plugin, I suppose)
- authentication:failed
- open_api:failure

`project:open` is currently NOT sent.

**Comment by jansorg** [comment]
In general, exceptions by the plugin are sent as GitHub issues after the user confirmed to send it. That's the way the JetBrains IDE's handle this (i.e. the manual confirmation before sending error reports to a server of the plugin's choice).


Possible errors:
- `authentication:failed`: Failure during/after sign in. This may indicate a problem with our sign in code, but there's no further context. It could also happen for server errors, I assume.
- `open_api:failure`: Sent if the AppMap CLI to generate OpenAPI did not return with exit code 0. It may indicate a problem with our code, e.g. when the CLI tool changed the supported command line.

No errors in our code:
- `run_config:incompatible_jdk`: This is about a problem with user's project. So this isn't a problem in our code.
- `run_config:execute`: A status message about run configuration execution. I wasn't sure if it should be removed, because it wasn't part of the VSCode refactor.

**Comment by kgilpin** [comment]
Ok thanks. Let’s drop `run_config:execute` and keep the other ones because they might be bugs in our code.
