### ISSUE TITLE
AppMaps are organized by category (recording method) similar to how VS Code does

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#421]
Needs detail - should be same as VS Code

**Comment by kgilpin** [comment]
He also wants the timestamps to be:

a) Consistent format eg ISO 8601 both in filenames and in the UI
b) Any date/time display in `ago` format for the last 24 hours - e.g. `1 minute ago`, `22 minutes ago`, `1 hour ago` etc

**Comment by brikelly** [comment]
@jansorg can you make this your next priority for this week?

**Comment by kgilpin** [comment]
Example:

<img width="428" alt="Screen Shot 2023-09-18 at 2 12 51 PM" src="https://github.com/getappmap/appmap-intellij-plugin/assets/86395/112d8ca2-a60f-4b8e-8a1a-019a239a406a">

**Comment by jansorg** [comment]
- Where should the timestamps be displayed? VSCode is showing the time only (including milliseconds!) if it's the current day (I think). Otherwise it's showing the date.
- Are timestamps only displayed for requests or also for items like queries?

![image](https://github.com/getappmap/appmap-intellij-plugin/assets/11473063/fe0aab82-1b20-4a1e-9d28-9d14df8809a1)

**Comment by kgilpin** [comment]
> How is VSCode building the tree hierarchy for AppMaps?

By project name, recorder type, recorder name. This information is available in the [AppMap metadata](https://github.com/getappmap/appmap#metadata) as recorder type and recorder name.

> Where should the timestamps be displayed? VSCode is showing the time only (including milliseconds!) if it's the current day (I think). Otherwise it's showing the date.

It's OK with me to follow the VSCode format since no-one has complained about it - yet :-)

> Are timestamps only displayed for requests or also for items like queries?

Timestamps can be shown for request recordings and remote recordings.

**Comment by jansorg** [comment]
@kgilpin How is "java"  in the screenshot above retrieved? Is it "language.name" of the metadata? If it's null, what's displayed instead?

**Comment by jansorg** [comment]
Is the timestamp the "last modified" time of the AppMap .appmap.json file?
