### ISSUE TITLE
Urls.newHttpUrl() uses scheme "http" by default

### ISSUE THREAD

**Issue by augustd** [getappmap/appmap-intellij-plugin#423]
In GitHubErrorHandler.submit() the application is constructing a URL using insecure http: 

https://github.com/getappmap/appmap-intellij-plugin/blob/17fa0bd14f1d5e7a218bad461c56d7b2ce5baadc/plugin-core/src/main/java/appland/GitHubErrorHandler.java#L58

The IntelliJ-provided method Urls.newHttpUrl() uses scheme:"http" when none is specified: 

```
  @JvmStatic
  fun newHttpUrl(authority: String, path: String?): Url = newUrl("http", authority, path)
```

Github will attempt to upgrade to HTTPS but only after the initial request has been sent. 

It is recommended to specify a scheme in the call to newHttpUrl():

```
var url = Urls.newHttpUrl("https", HOST, URL_PATH);
```

**Comment by jansorg** [comment]
@augustd Thanks! This will be fixed by https://github.com/getappmap/appmap-intellij-plugin/pull/426.
The fix is to call `Urls.newUrl("https", ...);` and not `Urls.newHttpUrl("https", ...);`, because the latter is defined like this:

```kotlin
@JvmStatic
  fun newHttpUrl(authority: String, path: String?, parameters: String?): Url = UrlImpl("http", authority, path, parameters)
```

But I only noticed because I made that mistake in my code, too ;)

**Comment by jansorg** [comment]
@brikelly 

## Testing
I've manually tested this.
It would be possible to write a test with a local mock server, but that would take some time, esp. with the enforced https connection.
It's not possible to let external testers test it because they would have to trigger an exception in the plugin's code.

**Comment by brikelly** [comment]
@jansorg that's fine, manual testing will be enough for now.
