### ISSUE TITLE
PyCharm fails to notify users when their first map is created

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#450]
PyCharm 2023.2.1 (Community Edition), MacOS, plugin v.0.50.0

With a fresh PyCharm install, I installed the AppMap plugin from the marketplace, installed AppMap into [this project](https://github.com/jainamoswal/Flask-Example), and ran `flask run`. AppMaps were created, but the user notification never appeared. 

The same plugin with a Java project in IntelliJ works correctly.

**Comment by jansorg** [comment]
@brikelly Could you eloborate what you did?

For example, this worked for me (macOS 12, latest PyCharm Professional, fresh clone of the project above):
1. Make sure that you removed the application settings because the notification is only shown once
2. I executed the install guide and ran the command by clicking the button
3. I had to refresh the requirements because the AppMap agent wasn't loaded apparently. PyCharm prompted me to do that when I opened `requirements.txt`.
4. I opened a terminal window and executed `flask run`
5. It printed a link to http://localhost:5000
6. I opened the link, which displayed "Hello Anonymous!"
7. I switched back to PyCharm
8. The notification about the first AppMap appeared

If that doesn't work for you, then I suppose the following could have caused it:
- The filewatcher of the IDE didn't pick up appmap.yml, which means that the AppMap CLI  processes were not launched to created the needed indexes. Is `appmap.yml` visible in the file tree in the project pane of PyCharm?
- The filewatcher did not pick up the new appmap data. When the terminal window is active, the filewatcher often only syncs with the filesystem when the focus is moved elsewhere. Are AppMaps displayed in the AppMap tool window and at `tmp/appmap` of the project pane?

**Comment by brikelly** [comment]
Thanks @jansorg, I can't reproduce this anymore. Will close this issue now.
