### ISSUE TITLE
Hover treatments for the top-right items are not working

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-intellij-plugin#476]
The hover treatments for the filter, export, controls etc are not working.

![Image](https://github.com/getappmap/appmap-intellij-plugin/assets/573108/00867ab6-5052-4cc5-a4e3-749f3543a59e)

**Comment by jansorg** [comment]
I can confirm this for 2023.2.3 and 2023.3 eap on MacOS. It's working on Linux, though.

Because the webview is fully controlled by the JetBrains JCEF integration we're unable to fix this. We could try to not use off-screen rendering for these versions on macOS, but that's likely to create other issues and complicates testing.

Bug report in JetBrains YouTrack: https://youtrack.jetbrains.com/issue/IDEA-328052/JCEF-browser-Tooltip-is-not-being-displayed
